
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodenotifier-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodenotifier-controller
  template:
    metadata:
      labels:
        app: nodenotifier-controller
    spec:
      serviceAccountName: nodenotifier-controller-sa
      containers:
      - name: nodenotifier-controller
        image: nodenotifier-controller
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-port
          containerPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodenotifier-controller-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodenotifier-controller-cluster-role
rules:
- apiGroups: ["mr.dopey"]
  resources: ["nodenotifiers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodenotifier-controller-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: nodenotifier-controller-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: nodenotifier-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io