apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodenotifiers.mr.dopey
spec:
  group: mr.dopey
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                label:
                  type: string
                slack-url:
                  type: string
  scope: Cluster
  names:
    plural: nodenotifiers
    singular: nodenotifier
    kind: NodeNotifier
    shortNames:
    - nn