apiVersion: mr.dopey/v1
kind: NodeNotifier
metadata:
  name: boxers
spec:
  label: minikube.k8s.io/name=minikube
  # TODO: should be a secret
  # Get webhook from: https://api.slack.com/messaging/webhooks
  slack-url: https://hooks.slack.com/services/XXXX